#!/usr/bin/env bash
# One-time aircraft camera pinning.
#
# Creates udev symlinks:
#   /dev/boresight    -> whichever /dev/videoN the boresight camera is on
#   /dev/depression   -> whichever /dev/videoN the depression camera is on
#
# Discriminator preference:
#   1) ID_SERIAL_SHORT   (unique per USB unit even for identical models)
#   2) USB port path     (KERNELS attribute) — fallback only
#
# Run once as root, at aircraft assembly:
#     sudo bash setup_cameras.sh
set -e
RULE_FILE=/etc/udev/rules.d/99-jetson-tracker-cameras.rules

if [ "$EUID" -ne 0 ]; then
    echo "Run as root: sudo bash $0"; exit 1
fi

CY='\033[0;36m'; GR='\033[0;32m'; YL='\033[1;33m'; RD='\033[0;31m'; NC='\033[0m'

wait_for_zero_cameras() {
    while ls /dev/video* >/dev/null 2>&1; do
        echo -e "${YL}  cameras still present, waiting...${NC}"; sleep 1
    done
}

# Poll until a *new* /dev/videoN appears that wasn't in $1.
wait_for_new_camera() {
    local existing="$1"
    while :; do
        local current=$(ls /dev/video* 2>/dev/null | sort)
        local new=$(comm -23 <(echo "$current") <(echo "$existing") | head -1)
        if [ -n "$new" ]; then
            echo "$new"; return 0
        fi
        sleep 1
    done
}

serial_of() { udevadm info -q property -n "$1" 2>/dev/null | awk -F= '$1=="ID_SERIAL_SHORT"{print $2}'; }
port_of()   { udevadm info -q path -n "$1" 2>/dev/null | grep -oE '/[0-9]+-[0-9]+(\.[0-9]+)*/' | tail -1 | tr -d /; }

echo -e "${CY}== Aircraft camera port pinning ==${NC}"

# ── Step 1 ────────────────────────────────────────────────
echo -e "${CY}Step 1/3: unplug BOTH cameras. Press Enter when done.${NC}"
read -r _
wait_for_zero_cameras

# ── Step 2 ────────────────────────────────────────────────
# Baseline captured now (empty), so wait_for_new_camera detects the first
# new node the moment the operator plugs in the BORESIGHT camera.
echo ""
echo -e "${CY}Step 2/3: plug in the BORESIGHT camera only, then press Enter.${NC}"
BASELINE=$(ls /dev/video* 2>/dev/null | sort)
read -r _
BORE_DEV=$(wait_for_new_camera "$BASELINE")
BORE_SN=$(serial_of "$BORE_DEV")
BORE_PORT=$(port_of "$BORE_DEV")
echo -e "${GR}  BORESIGHT  : $BORE_DEV${NC}"
echo -e "${GR}    serial    : ${BORE_SN:-<none>}${NC}"
echo -e "${GR}    port path : ${BORE_PORT:-<unknown>}${NC}"

# ── Step 3 ────────────────────────────────────────────────
# Capture baseline BEFORE the prompt so plugging in either before or
# after the Enter press still works — anything not in the baseline
# after Enter is the new camera.
echo ""
echo -e "${CY}Step 3/3: now plug in the DEPRESSION camera, then press Enter.${NC}"
BASELINE=$(ls /dev/video* 2>/dev/null | sort)
read -r _
DEP_DEV=$(wait_for_new_camera "$BASELINE")
DEP_SN=$(serial_of "$DEP_DEV")
DEP_PORT=$(port_of "$DEP_DEV")
echo -e "${GR}  DEPRESSION : $DEP_DEV${NC}"
echo -e "${GR}    serial    : ${DEP_SN:-<none>}${NC}"
echo -e "${GR}    port path : ${DEP_PORT:-<unknown>}${NC}"

# ── Choose discriminator ──────────────────────────────────
USE_SERIAL=0
if [ -n "$BORE_SN" ] && [ -n "$DEP_SN" ] && [ "$BORE_SN" != "$DEP_SN" ]; then
    USE_SERIAL=1
    echo ""
    echo -e "${CY}Using USB serial numbers to key the udev rule.${NC}"
elif [ -n "$BORE_PORT" ] && [ -n "$DEP_PORT" ] && [ "$BORE_PORT" != "$DEP_PORT" ]; then
    echo ""
    echo -e "${CY}Serials missing or identical — falling back to USB port path.${NC}"
else
    echo ""
    echo -e "${RD}Cannot distinguish the two cameras:${NC}"
    echo -e "${RD}  serials  : '$BORE_SN' vs '$DEP_SN'${NC}"
    echo -e "${RD}  ports    : '$BORE_PORT' vs '$DEP_PORT'${NC}"
    echo -e "${RD}Try plugging them into two independent Jetson USB ports.${NC}"
    exit 1
fi

# ── Write rule ────────────────────────────────────────────
if [ "$USE_SERIAL" = "1" ]; then
    cat > "$RULE_FILE" <<EOF
# Generated by setup_cameras.sh on $(date -Iseconds).
# Keyed on USB serial number — survives cable/port reseats.
SUBSYSTEM=="video4linux", ENV{ID_SERIAL_SHORT}=="$BORE_SN", ATTR{index}=="0", SYMLINK+="boresight"
SUBSYSTEM=="video4linux", ENV{ID_SERIAL_SHORT}=="$DEP_SN",  ATTR{index}=="0", SYMLINK+="depression"
EOF
else
    cat > "$RULE_FILE" <<EOF
# Generated by setup_cameras.sh on $(date -Iseconds).
# Keyed on USB port path — moving a camera to a different port breaks the mapping.
SUBSYSTEM=="video4linux", KERNELS=="$BORE_PORT", ATTR{index}=="0", SYMLINK+="boresight"
SUBSYSTEM=="video4linux", KERNELS=="$DEP_PORT",  ATTR{index}=="0", SYMLINK+="depression"
EOF
fi

echo ""
echo -e "${GR}Wrote $RULE_FILE${NC}"
cat "$RULE_FILE"

udevadm control --reload-rules
udevadm trigger --subsystem-match=video4linux
sleep 1

echo ""
echo -e "${CY}Verification:${NC}"
if ls -l /dev/boresight /dev/depression 2>/dev/null; then
    echo -e "${GR}  OK — stable symlinks present.${NC}"
else
    echo -e "${YL}  Symlinks not yet visible — replug the cameras or reboot.${NC}"
fi
